apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-cli-jq
  labels:
    app: argocd-cli-jq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-cli-jq
  template:
    metadata:
      labels:
        app: argocd-cli-jq
    spec:
      containers:
      - name: argocd-cli-jq
        image: hepapi/argocd-cli-jq:main
        command: ["sleep", "inf"]
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"