# comment out the timeZone if you want to keep things default
timeZone: 'Asia/Istanbul'
schedule: "00 20 * * *"

serviceAccount: argocd-server

secrets:
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_DEFAULT_REGION: ""
  ARGOCD_SERVER: ""
  ADMIN_PASSWORD: ""
  S3_UPLOAD_PREFIX: ""
  S3_BUCKET_NAME: ""


resources:
  limits:
    memory: "256Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

image:
  repository: "ghcr.io/oguzhan-yilmaz/argocd-backup-s3"
  tag: "latest"
  pullPolicy: Always