apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-backup-s3
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - get     # supports viewing live object manifest in UI
      - patch   # supports `argocd app patch`
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - list
      - create
  - apiGroups:
      - argoproj.io
    resources:
      - applications
      - applicationsets
    verbs:
      - get
      - list
      - update
      - watch