apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-backup-s3
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - applications
      - applicationsets
      - clusters
      - repositories
      - appprojects
      - projects
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - list